//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_Taches.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONNE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PERSONNE()
        {
            this.TACHEs = new HashSet<TACHE>();
        }
    
        public int CIN { get; set; }
        public Nullable<decimal> ID_DEPARTEMENT { get; set; }
        public Nullable<decimal> ID_SERV { get; set; }
        public string NOM { get; set; }
        public string PRENOM { get; set; }
        public Nullable<int> AGE { get; set; }
        public string ADRESSE { get; set; }
        public Nullable<int> TEL { get; set; }
        public string MAIL { get; set; }
        public Nullable<System.DateTime> DATE_NAIS { get; set; }
    
        public virtual DEPARTEMENT DEPARTEMENT { get; set; }
        public virtual SERVICE SERVICE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TACHE> TACHEs { get; set; }
    }
}
