//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gestion_de_Taches.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TACHE
    {
        public decimal ID_TACHE { get; set; }
        public Nullable<int> CIN { get; set; }
        public Nullable<System.DateTime> DATE_DEBUT { get; set; }
        public Nullable<System.DateTime> DATE_FIN { get; set; }
        public string DESCIPTION { get; set; }
    
        public virtual PERSONNE PERSONNE { get; set; }
    }
}
